(function () {
  'use strict';
  var API_BASE=(location.protocol==='file:')?'http://localhost:3000/api':'/api',TOKEN_KEY='rota1615_admin_token';
  var loginScreen=document.getElementById('loginScreen'),adminApp=document.getElementById('adminApp'),loginForm=document.getElementById('loginForm'),loginFeedback=document.getElementById('loginFeedback'),loginSubmit=document.getElementById('loginSubmit');
  function getToken(){return sessionStorage.getItem(TOKEN_KEY);} function setToken(t){sessionStorage.setItem(TOKEN_KEY,t);} function clearToken(){sessionStorage.removeItem(TOKEN_KEY);}
  function authFetch(path,options){options=options||{};options.headers=Object.assign({},options.headers,{Authorization:'Bearer '+getToken()});return fetch(API_BASE+path,options).then(function(res){if(res.status===401){clearToken();showLogin('Sessão expirada. Faça login novamente.');throw new Error('unauthorized');}return res;});}
  function showLogin(m){adminApp.hidden=true;loginScreen.hidden=false;if(m)loginFeedback.textContent=m;} function showApp(){loginScreen.hidden=true;adminApp.hidden=false;loadOrders();loadVipList();loadProducts();}
  function escapeHtml(v){var d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;} function formatBRL(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);}
  loginForm.addEventListener('submit',function(e){e.preventDefault();loginSubmit.disabled=true;loginFeedback.textContent='';fetch(API_BASE+'/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:document.getElementById('loginPassword').value})}).then(function(r){return r.json().then(function(d){return{ok:r.ok,data:d};});}).then(function(r){loginSubmit.disabled=false;if(r.ok){setToken(r.data.token);loginForm.reset();showApp();}else loginFeedback.textContent=r.data.message||'Não foi possível entrar.';}).catch(function(){loginSubmit.disabled=false;loginFeedback.textContent='Não foi possível conectar ao servidor.';});});
  document.getElementById('logoutBtn').addEventListener('click',function(){authFetch('/admin/logout',{method:'POST'}).catch(function(){}).then(function(){clearToken();showLogin('');});});
  document.querySelectorAll('.tab-btn').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.tab-btn').forEach(function(b){b.setAttribute('aria-pressed','false');});btn.setAttribute('aria-pressed','true');document.querySelectorAll('.tab-panel').forEach(function(p){p.hidden=true;});document.getElementById('tab-'+btn.dataset.tab).hidden=false;});});

  var ORDER_STATUSES=['pendente','confirmado','enviado','concluido','cancelado'],ORDER_STATUS_LABELS={pendente:'Pendente',confirmado:'Confirmado',enviado:'Enviado',concluido:'Concluído',cancelado:'Cancelado'},PAYMENT_LABELS={pending:'Pendente',approved:'Aprovado',rejected:'Recusado',cancelled:'Cancelado',refunded:'Estornado',error:'Erro'};
  function loadOrders(){authFetch('/admin/orders').then(function(r){if(!r.ok)throw new Error();return r.json();}).then(renderOrdersTable).catch(function(){});}
  function renderOrdersTable(orders){var body=document.getElementById('ordersTableBody'),empty=document.getElementById('ordersEmpty');document.getElementById('ordersCount').textContent=orders.length+(orders.length===1?' pedido':' pedidos');body.innerHTML='';empty.hidden=!!orders.length;orders.forEach(function(o){var tr=document.createElement('tr'),date=new Date(o.createdAt),items=(o.items||[]).map(function(i){return i.qty+'x '+i.name;}).join(', '),statusOptions=ORDER_STATUSES.map(function(s){return'<option value="'+s+'" '+(s===o.status?'selected':'')+'>'+ORDER_STATUS_LABELS[s]+'</option>';}).join('');tr.innerHTML='<td data-label="Cliente">'+escapeHtml(o.customer.name)+'<br><span class="row-sub">'+escapeHtml(o.customer.email)+' · '+escapeHtml(o.customer.phone)+'<br>'+escapeHtml(o.customer.address)+'</span></td><td data-label="Itens"><span class="row-sub">'+escapeHtml(items)+'</span></td><td data-label="Total">'+formatBRL(o.total)+'</td><td data-label="Status"><select class="status-select" data-id="'+o.id+'">'+statusOptions+'</select></td><td data-label="Pagamento"><span class="row-sub">'+escapeHtml(PAYMENT_LABELS[o.paymentStatus]||o.paymentStatus||'-')+(o.paymentId?'<br>#'+escapeHtml(o.paymentId):'')+'</span></td><td data-label="Data"><span class="row-sub">'+date.toLocaleDateString('pt-BR')+' '+date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+'</span></td><td><div class="row-actions"><button class="icon-btn danger" data-id="'+o.id+'">Remover</button></div></td>';body.appendChild(tr);});body.querySelectorAll('.status-select').forEach(function(s){s.addEventListener('change',function(){authFetch('/admin/orders/'+s.dataset.id+'/status',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s.value})}).then(function(r){if(!r.ok)throw new Error();return r.json();}).then(loadOrders).catch(function(){loadOrders();});});});body.querySelectorAll('.icon-btn.danger').forEach(function(b){b.addEventListener('click',function(){if(!confirm('Remover este pedido?'))return;authFetch('/admin/orders/'+b.dataset.id,{method:'DELETE'}).then(loadOrders).catch(function(){});});});}

  var vipData=[];
  function loadVipList(){authFetch('/admin/vip').then(function(r){return r.json().then(function(d){if(!r.ok)throw new Error(d.message||'Erro ao carregar lista VIP');return d;});}).then(function(d){vipData=Array.isArray(d)?d:[];renderVipTable();}).catch(function(err){console.error('[VIP]',err);var empty=document.getElementById('vipEmpty');if(empty){empty.hidden=false;empty.textContent='Não foi possível carregar a lista VIP. Veja o Console para o erro.';}});}
  function renderVipTable(){var body=document.getElementById('vipTableBody'),empty=document.getElementById('vipEmpty');document.getElementById('vipCount').textContent=vipData.length+(vipData.length===1?' inscrito':' inscritos');body.innerHTML='';empty.hidden=!!vipData.length;vipData.forEach(function(e){var tr=document.createElement('tr');tr.innerHTML='<td data-label="Nome">'+escapeHtml(e.name)+'</td><td data-label="E-mail">'+escapeHtml(e.email)+'</td><td data-label="Inscrito em">'+(e.createdAt ? new Date(e.createdAt).toLocaleString('pt-BR') : '—')+'</td><td><div class="row-actions"><button class="icon-btn danger" data-id="'+e.id+'">Remover</button></div></td>';body.appendChild(tr);});body.querySelectorAll('.icon-btn.danger').forEach(function(b){b.addEventListener('click',function(){if(!confirm('Remover este inscrito da lista VIP?'))return;authFetch('/admin/vip/'+b.dataset.id,{method:'DELETE'}).then(loadVipList).catch(function(){});});});}
  document.getElementById('exportCsv').addEventListener('click',function(){if(!vipData.length)return;var rows=[['Nome','E-mail','Inscrito em']].concat(vipData.map(function(e){return[e.name,e.email,e.createdAt];}));var csv=rows.map(function(r){return r.map(function(c){return'"'+String(c).replace(/"/g,'""')+'"';}).join(',');}).join('\n');var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));a.download='rota1615-lista-vip.csv';a.click();});

  var productForm=document.getElementById('productForm'),productFeedback=document.getElementById('productFeedback'),productSubmit=document.getElementById('productSubmit'),productCancel=document.getElementById('productCancel'),editingId=null,catLabels={camisetas:'Camisetas',moletons:'Moletons',bermudas:'Bermudas',acessorios:'Acessórios'};
  function loadProducts(){authFetch('/admin/products').then(function(r){return r.json();}).then(renderProductsTable).catch(function(){});}
  function renderProductsTable(products){var body=document.getElementById('productsTableBody'),empty=document.getElementById('productsEmpty');body.innerHTML='';empty.hidden=!!products.length;products.forEach(function(p){var tr=document.createElement('tr');tr.innerHTML='<td data-label="Nome">'+escapeHtml(p.name)+'</td><td data-label="Categoria">'+escapeHtml(catLabels[p.category]||p.category)+'</td><td data-label="Preço">'+formatBRL(p.price)+'</td><td data-label="Estoque">'+p.stock+'</td><td><div class="row-actions"><button class="icon-btn" data-action="edit">Editar</button><button class="icon-btn danger" data-action="delete">Remover</button></div></td>';body.appendChild(tr);tr.querySelector('[data-action="edit"]').addEventListener('click',function(){editingId=p.id;document.getElementById('pName').value=p.name;document.getElementById('pCategory').value=p.category;document.getElementById('pPrice').value=p.price;document.getElementById('pStock').value=p.stock;document.getElementById('pImage').value=p.image||'';document.getElementById('pDescription').value=p.description||'';productSubmit.textContent='Salvar alterações';productCancel.hidden=false;document.getElementById('pName').focus();});tr.querySelector('[data-action="delete"]').addEventListener('click',function(){if(!confirm('Remover "'+p.name+'" do catálogo?'))return;authFetch('/admin/products/'+p.id,{method:'DELETE'}).then(function(r){if(!r.ok)throw new Error();loadProducts();}).catch(function(){productFeedback.textContent='Não foi possível remover o produto.';productFeedback.className='form-feedback err';});});});}
  function resetProductForm(){editingId=null;productForm.reset();productSubmit.textContent='Adicionar produto';productCancel.hidden=true;} productCancel.addEventListener('click',resetProductForm);
  productForm.addEventListener('submit',function(e){e.preventDefault();var payload={name:document.getElementById('pName').value.trim(),category:document.getElementById('pCategory').value,price:Number(document.getElementById('pPrice').value),stock:Number(document.getElementById('pStock').value),image:document.getElementById('pImage').value.trim()||null,description:document.getElementById('pDescription').value.trim()||null};if(!payload.name||!Number.isFinite(payload.price)||!Number.isInteger(payload.stock)||payload.stock<0){productFeedback.textContent='Preencha nome, preço e estoque corretamente.';productFeedback.className='form-feedback err';return;}productSubmit.disabled=true;var req=editingId?authFetch('/admin/products/'+editingId,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}):authFetch('/admin/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});req.then(function(r){return r.json().then(function(d){return{ok:r.ok,data:d};});}).then(function(r){productSubmit.disabled=false;if(!r.ok){productFeedback.textContent=r.data.message||'Não foi possível salvar.';productFeedback.className='form-feedback err';return;}productFeedback.textContent=editingId?'Produto atualizado.':'Produto adicionado.';productFeedback.className='form-feedback ok';resetProductForm();loadProducts();}).catch(function(){productSubmit.disabled=false;productFeedback.textContent='Não foi possível conectar ao servidor.';productFeedback.className='form-feedback err';});});
  if(getToken())showApp();else showLogin('');
})();
